export const ActionTypes = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  TOGGLE_EDIT_TODO: "TOGGLE_EDIT_TODO",
  SAVE_TODO: "SAVE_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  DELETE_COMPLETED_TODO: "DELETE_COMPLETED_TODO",
  DELETE_ALL_COMPLETED_TODO: "DELETE_ALL_COMPLETED_TODO",
}
